{% set version = "1.2.6" %}

package:
  name: pyxb
  version: {{ version }}

source:
  fn: PyXB-{{ version }}.tar.gz
  url: https://github.com/pabigot/pyxb/archive/PyXB-{{ version }}.tar.gz
  sha256: 034871fae8935de0b38a613e162dab2382da71ff7b182f34f78f595cafc4a670

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python

test:
  requires:
    - nose
  imports:
    - pyxb
  source_files:
    - setup.py
    - pyxb/binding
    - tests
  commands:
    - python setup.py test  # [not win]
    # skips testing on win, due to known test failures related to:
    # https://github.com/pabigot/pyxb/issues/34

about:
  home: http://pyxb.sourceforge.net
  license: Apache 2.0
  summary: PyXB ("pixbee") is a pure Python package that generates Python source code for classes that correspond to data structures defined by XMLSchema.
  dev_url: https://github.com/pabigot/pyxb
  license_file: LICENSE

extra:
  recipe-maintainers:
    - grlee77
