travis:
  secure:
    BINSTAR_TOKEN: DfMSz2GbkuJZh3YIqJ1kC5Qqh/7c+X3kjrX6HNJMHX00FPRhwbm+ZeSFWLv5sPxhQqM9ZaZNE3cL/0LACwkhduqypj48VE+ruLo1DR2NfDq9KQ7v29kxeKOfwybLI2JgYLxYAIexF9Ha9d+iDuXyN5CfagexVAdflopSFCCksdCg4KaKAOCdiRiFsShVU1mmhDn9KUicSMrXF7eBHezMyV1li0EBU7Y5gIf3PLSSd7HgFPSSdaN9w8xaRrGjt4RM2fVzv0ZozXL3l6B9zUTXRQXZ+L2fjmypiNgsp/fWGzIIqEQEhtXp6WfToVvb4XW1QI7vI18qAlpnX089/ELG4wTcrB9GJeMeU7EWRkubokmBVdgvo5ahLfIEClAcWS9TzHyWD2WLjg1DXAcPzmv3aU+gCxhpFgvW38H8lklXXaQJrTE+JRWYSk3ZBZasozrEYPaZExUxAXGPrcFFCrIny2e3+1EGDFoeaBMj6oln84N4AjoLZVp4aNMuEHzQpwKsVZraFL1n7PeTm7OTIQE4kJhLYhu8httsf6TrtvG0PQ90QnKf0Tx53vSSW3q4JbcVnX7eAIzHa/LYLGlGZ/+cHlpYJRIHRYBC0VR77Z3GzIzQBmUA/h3K2g1peoX5UiNxw0ay+W5864tIDlH3Q9faE/Evk1+CJKtgOAnSi31kEq0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
