travis:
  secure:
    BINSTAR_TOKEN: LxSLxnADfNSS5QGXu5xfVXitAsZKXYCykLD+jyUUwgOdP1uKdcseWcHdhj66GdJFl/KuPEU21dMpt36QFtsNbU6ZdZiilrbT7gA8KE5916HyKRuGBAFZ/t/afi8ioIs73Suc+NJ7Wm5F5KMvbEFLN1TBGBf46HC9nKPtV1MYKSG300bywLmALjFUeLY/IRlKR+2sHQCps4VEE7wQqHpP60SlgPY8pbgrW9wA9bCs14unXZGLlE7+sPioSMa5w7U2pa+p9iiFcn2SaAXw2N5kR1uo3g63oodOsKo9POSZYn6Y4nlr2o9kKGhynUla7NifO1qb2TSEDVVBNmxAlQXqZUwKmvexW/kILWcZ/j/3ltAo9t0tEpvN8euFXe2hZiXN8QxHI0VEPlWkG9JvEWVRVT/dofAj2WFF+1Bt6Euet0RfqpN4MWoFXZ1DU+2QzgfJLLxSTm+/usuOIaGiZsQw6n9W0O94fNIHYnx2akgVcmL7thD0LkBXnntGTo4sz+4QO8655wR9notksvE/rqnmpfYeOf3LD4vX1JjKeBRTy6jzoiyy8nk3zQa8qjjAY2cAgL6IhOOaMJVQxihWdg9x94tmx6kJvCTTZ8jTdpBAJm0MGZqqWCepNXC8jIpxK/X7YonAEEsm/b7h9klidHGX7m9xfvV+PaxY3RXzi+RGyhc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
