travis:
  secure:
    BINSTAR_TOKEN: JoMqE6DrG8hulg8B+Br8UQAzFXN5V8qI8VME5u8HKr3gCO7zGjC6aGKzRMc85BS2bUFOxfUwpPgY/9E7pq+SWBxd6lDqu/DK6xkhPTIvxRGEJfFQhgqtN5YDuvyIRNJ6P3LuHD9XappQYAFodne4vITE6F3d5rnPMjTEUsgSlbcp71D8msC3AF+HN1fSnCAy8Zic7R3v3+E+q7x1GL8NtkyO9oKYP1fR4dovjtW5oJn1jO1aCyI6U88ggnd/ZwS5g9+byDZPizJpJg3P3KBUmmU4IsBAGk+1Kzp5+bCzje1L8J1eGe6pJIXywmOZI+CZaPFwJIYSPGB+M8E+9BFcY9Ul7Y6BtCwvHlfgvPvwMyX1CYElSw7fXmvfVac+47Jf3T/xgcDHhqtGG6DdXABjqkRSmFusNkDANnzcr0/3lXe1OMvJm4HPVoe3oHdEPM+ZS09XK/VXE/YD2uFasyfDn5QNvRwbQhRsOR3FkzxSXFfWnjVTFP82Lo2wR+gmBzzbChPSRJsKPGh4kRTb/0bWL/pOm3Ebq776mjCFueWYs4LkPBsSmOP0uLlgZnVDZgAPqdFg1CACB9nL5cBIAXj/D0Kpond74RdOF26UCnLAtxa1QT41zi9u80UtOY9YMPWzVU5nVMcdmfJuxM76zC6q3Qw7RT8yXH28/k8CfFPupac=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
